export const NBEVERAGES_TOKEN = 'NBEVERAGES_TOKEN';
export const NBEVERAGES_SHOPPING_CART = 'NBEVERAGES_SHOPPING_CART';

export const PAGE_ADMIN = '/secret-section';
export const PAGE_ADMIN_ORDERS = '/secret-section/orders';
export const PAGE_ORDER = '/order';

export const NAVIGATION_LINK_HOME = 'NAVIGATION_LINK_HOME';
export const NAVIGATION_LINK_CATALOG = 'NAVIGATION_LINK_CATALOG';
export const NAVIGATION_LINK_CONTACT = 'NAVIGATION_LINK_CONTACT';
export const NAVIGATION_LINK_ADMIN = 'NAVIGATION_LINK_ADMIN';
export const NAVIGATION_LINK_LOGIN = 'NAVIGATION_LINK_LOGIN';
export const NAVIGATION_LINK_LOGOUT = 'NAVIGATION_LINK_LOGOUT';
export const NAVIGATION_LINK_SHOPPING_CART = 'NAVIGATION_LINK_SHOPPING_CART';
export const NAVIGATION_LINK_CHECK_ORDER_STATUS = 'NAVIGATION_LINK_CHECK_ORDER_STATUS';

export const FILTER_CATEGORY = 'FILTER_CATEGORY';
export const FILTER_TYPE = 'FILTER_TYPE';

export const BUTTON_CAPTION_ADD = 'BUTTON_CAPTION_ADD';
export const BUTTON_CAPTION_REMOVE = 'BUTTON_CAPTION_REMOVE';

export const MAIN_WELCOME_HEADER = 'MAIN_WELCOME_HEADER';
export const MAIN_WELCOME_MESSAGE = 'MAIN_WELCOME_MESSAGE';
export const MAIN_ORDER_STATUS = 'MAIN_ORDER_STATUS';
export const MAIN_VISIT = 'MAIN_VISIT';
export const MAIN_TEA_DESCRIPTION = 'MAIN_TEA_DESCRIPTION';

export const SHOPPING_CART_CUSTOMER_NAME = 'SHOPPING_CART_CUSTOMER_NAME';
export const SHOPPING_CART_PAYMENT_METHOD = 'SHOPPING_CART_PAYMENT_METHOD';
export const SHOPPING_CART_PHONE_NUMBER = 'SHOPPING_CART_PHONE_NUMBER';
export const SHOPPING_CART_EMAIL = 'SHOPPING_CART_EMAIL';
export const SHOPPING_CART_DELIVERY_METHOD = 'SHOPPING_CART_DELIVERY_METHOD';
export const SHOPPING_CART_SELECT_PICKUP_POINT = 'SHOPPING_CART_SELECT_PICKUP_POINT';
export const SHOPPING_CART_ENTER_DELIVERY_ADDRESS = 'SHOPPING_CART_ENTER_DELIVERY_ADDRESS';
export const SHOPPING_CART_ORDER = 'SHOPPING_CART_ORDER';
export const SHOPPING_CART_DELIVERY_ADDRESS_PLACEHOLDER = 'SHOPPING_CART_DELIVERY_ADDRESS_PLACEHOLDER';
export const SHOPPING_CART_PRODUCT_NAME = 'SHOPPING_CART_PRODUCT_NAME';
export const SHOPPING_CART_PRODUCT_DESCRIPTION = 'SHOPPING_CART_PRODUCT_DESCRIPTION';
export const SHOPPING_CART_PRODUCT_QUANTITY = 'SHOPPING_CART_PRODUCT_QUANTITY';
export const SHOPPING_CART_ITEM_QUANTITY_PER_UNIT = 'SHOPPING_CART_ITEM_QUANTITY_PER_UNIT';
export const SHOPPING_CART_ITEM_QUANTITY = 'SHOPPING_CART_ITEM_QUANTITY';
export const SHOPPING_CART_PRODUCT_PRICE = 'SHOPPING_CART_PRODUCT_PRICE';
export const SHOPPING_CART_TOTAL_PRICE = 'SHOPPING_CART_TOTAL_PRICE';
export const SHOPPING_CART_CUSTOMER_FORM_NAME = 'SHOPPING_CART_CUSTOMER_FORM_NAME';
export const SHOPPING_CART_PRODUCT_QUANTITY_PER_UNIT = 'SHOPPING_CART_PRODUCT_QUANTITY_PER_UNIT';
export const SHOPPING_CART_NO_ITEMS = 'SHOPPING_CART_NO_ITEMS';

export const LOGIN_PASSWORD = 'LOGIN_PASSWORD';

export const ADMIN_CATALOG = 'ADMIN_CATALOG';
export const ADMIN_ORDERS = 'ADMIN_ORDERS';
export const ADMIN_ITEM_TYPE = 'ADMIN_ITEM_TYPE';
export const ADMIN_ITEM_IMG_SRC = 'ADMIN_ITEM_IMG_SRC';
export const ADMIN_ITEM_NAME = 'ADMIN_ITEM_NAME';
export const ADMIN_ITEM_DESCRIPTION = 'ADMIN_ITEM_DESCRIPTION';
export const ADMIN_ITEM_QUANTITY_PER_UNIT = 'ADMIN_ITEM_QUANTITY_PER_UNIT';
export const ADMIN_ITEM_PRICE = 'ADMIN_ITEM_PRICE';
export const ADMIN_ITEM_CURRENCY = 'ADMIN_ITEM_CURRENCY';
export const ADMIN_ITEM_CATEGORY = 'ADMIN_ITEM_CATEGORY';
export const ADMIN_ITEM_ADD_BUTTON = 'ADMIN_ITEM_ADD_BUTTON';
export const ADMIN_ITEM_BUTTON_UPDATE = 'ADMIN_ITEM_BUTTON_UPDATE';
export const ADMIN_ITEM_BUTTON_CLOSE = 'ADMIN_ITEM_BUTTON_CLOSE';
export const ADMIN_ITEM_BUTTON_DELETE = 'ADMIN_ITEM_BUTTON_DELETE';

export const BEVERAGE_SHORT_VIEW_QUANTITY_PER_UNIT = 'BEVERAGE_SHORT_VIEW_QUANTITY';
export const BEVERAGE_SHORT_VIEW_QUANTITY_BOXING = 'BEVERAGE_SHORT_VIEW_QUANTITY_BOXING';
export const BEVERAGE_SHORT_VIEW_QUANTITY_PRICE = 'BEVERAGE_SHORT_VIEW_QUANTITY_PRICE';

export const DELIVERY_METHODS_PLACEHOLDER = 'DELIVERY_METHODS_PLACEHOLDER';
export const DELIVERY_METHODS_DELIVERY = 'DELIVERY_METHODS_DELIVERY';
export const DELIVERY_METHODS_PICKUP = 'DELIVERY_METHODS_PICKUP';

export const PICKUP_ADDRESS_PLACEHOLDER = 'PICKUP_ADDRESS_PLACEHOLDER';

export const PAYMENT_METHODS_PLACEHOLDER = 'PAYMENT_METHODS_PLACEHOLDER';
export const PAYMENT_METHODS_CASH = 'PAYMENT_METHODS_CASH';
export const PAYMENT_METHODS_CREDIT_CARD = 'PAYMENT_METHODS_CREDIT_CARD';

export const CATALOG_ITEM_QUANTITY_PER_UNIT = 'CATALOG_ITEM_QUANTITY_PER_UNIT';
export const CATALOG_ITEM_DESCRIPTION = 'CATALOG_ITEM_DESCRIPTION';
export const CATALOG_ITEM_BUTTON_ADD_TO_CART = 'CATALOG_ITEM_BUTTON_ADD_TO_CART';
export const CATALOG_ITEM_PRICE = 'CATALOG_ITEM_PRICE';

export const ORDER_PAGE_ORDER_ID = 'ORDER_PAGE_ORDER_ID';
export const ORDER_PAGE_ORDER_STATUS = 'ORDER_PAGE_ORDER_STATUS';
export const ORDER_PAGE_CUSTOMER_NAME = 'ORDER_PAGE_CUSTOMER_NAME';
export const ORDER_PAGE_CUSTOMER_EMAIL = 'ORDER_PAGE_CUSTOMER_EMAIL';
export const ORDER_PAGE_CUSTOMER_PHONE = 'ORDER_PAGE_CUSTOMER_PHONE';
export const ORDER_PAGE_DELIVERY_METHOD = 'ORDER_PAGE_DELIVERY_METHOD';
export const ORDER_PAGE_DELIVERY_ADDRESS = 'ORDER_PAGE_DELIVERY_ADDRESS';
export const ORDER_PAGE_PAYMENT_METHOD = 'ORDER_PAGE_PAYMENT_METHOD';
export const ORDER_PAGE_BUTTON_SEARCH = 'ORDER_PAGE_BUTTON_SEARCH';

export const HEADER_WORKING_HOURS = 'HEADER_WORKING_HOURS';

export const ADMIN_CATALOG_HEADER_IMAGE = 'ADMIN_CATALOG_HEADER_IMAGE';
export const ADMIN_CATALOG_HEADER_CATEGORY = 'ADMIN_CATALOG_HEADER_CATEGORY';
export const ADMIN_CATALOG_HEADER_TYPE = 'ADMIN_CATALOG_HEADER_TYPE';
export const ADMIN_CATALOG_HEADER_CUSTOMER = 'ADMIN_CATALOG_HEADER_CUSTOMER';
export const ADMIN_CATALOG_HEADER_ITEM_NAME = 'ADMIN_CATALOG_HEADER_ITEM_NAME';
export const ADMIN_CATALOG_HEADER_DESCRIPTION = 'ADMIN_CATALOG_HEADER_DESCRIPTION';
export const ADMIN_CATALOG_HEADER_QUANTITY_PER_UNIT = 'ADMIN_CATALOG_HEADER_QUANTITY_PER_UNIT';
export const ADMIN_CATALOG_QUANTITY_PER_UNIT = 'ADMIN_CATALOG_QUANTITY_PER_UNIT';
export const ADMIN_CATALOG_HEADER_PRICE = 'ADMIN_CATALOG_HEADER_PRICE';

export const TABLE_BUTTON_PREV = 'TABLE_BUTTON_PREV';
export const TABLE_BUTTON_NEXT = 'TABLE_BUTTON_NEXT';
export const TABLE_NO_DATA_TEXT = 'TABLE_NO_DATA_TEXT';
export const TABLE_OF_TEXT = 'TABLE_OF_TEXT';
export const TABLE_ROWS_TEXT = 'TABLE_ROWS_TEXT';
export const TABLE_PAGE_TEXT = 'TABLE_PAGE_TEXT';

export const ORDER_ITEM_HEADER = 'ORDER_ITEM_HEADER';
export const ORDER_ITEM_BUTTON_UPDATE = 'ORDER_ITEM_BUTTON_UPDATE';
export const ORDER_ITEM_BUTTON_DELETE = 'ORDER_ITEM_BUTTON_DELETE';

export const BEVERAGE_CATEGORY_SELECT_PLACEHOLDER = 'BEVERAGE_CATEGORY_SELECT_PLACEHOLDER';
export const BEVERAGE_CATEGORY_TEA = 'BEVERAGE_CATEGORY_TEA';
export const BEVERAGE_CATEGORY_COFFEE = 'BEVERAGE_CATEGORY_COFFEE';

export const BEVERAGE_TYPES_SELECT_PLACEHOLDER = 'BEVERAGE_TYPES_SELECT_PLACEHOLDER';
export const BEVERAGE_TYPES_GREEN = 'BEVERAGE_TYPES_GREEN';
export const BEVERAGE_TYPES_BLACK = 'BEVERAGE_TYPES_BLACK';
export const BEVERAGE_TYPES_RED = 'BEVERAGE_TYPES_RED';
export const BEVERAGE_TYPES_HERBAL = 'BEVERAGE_TYPES_HERBAL';

export const BEVERAGE_TYPES_ARABIC = 'BEVERAGE_TYPES_ARABIC';

export const CURRENCY_USD = 'CURRENCY_USD';
export const CURRENCY_BYN = 'CURRENCY_BYN';
export const CURRENCY_SELECT_PLACEHOLDER = 'CURRENCY_SELECT_PLACEHOLDER';
