export const NBEVERAGES_TOKEN = 'NBEVERAGES_TOKEN';
export const NBEVERAGES_SHOPPING_CART = 'NBEVERAGES_SHOPPING_CART';

export const PAGE_ADMIN = '/secret-section';
export const PAGE_ADMIN_ORDERS = '/secret-section/orders';
export const PAGE_ORDER = '/order';

export const NAVIGATION_LINK_HOME = 'NAVIGATION_LINK_HOME';
export const NAVIGATION_LINK_CATALOG = 'NAVIGATION_LINK_CATALOG';
export const NAVIGATION_LINK_CONTACT = 'NAVIGATION_LINK_CONTACT';
export const NAVIGATION_LINK_ADMIN = 'NAVIGATION_LINK_ADMIN';
export const NAVIGATION_LINK_LOGIN = 'NAVIGATION_LINK_LOGIN';
export const NAVIGATION_LINK_LOGOUT = 'NAVIGATION_LINK_LOGOUT';
export const NAVIGATION_LINK_SHOPPING_CART = 'NAVIGATION_LINK_SHOPPING_CART';
export const NAVIGATION_LINK_CHECK_ORDER_STATUS = 'NAVIGATION_LINK_CHECK_ORDER_STATUS';

export const FILTER_CATEGORY = 'FILTER_CATEGORY';
export const FILTER_TYPE = 'FILTER_TYPE';

export const BUTTON_CAPTION_ADD = 'BUTTON_CAPTION_ADD';
export const BUTTON_CAPTION_REMOVE = 'BUTTON_CAPTION_REMOVE';

export const MAIN_WELCOME_HEADER = 'MAIN_WELCOME_HEADER';
export const MAIN_WELCOME_MESSAGE = 'MAIN_WELCOME_MESSAGE';
export const MAIN_ORDER_STATUS = 'MAIN_ORDER_STATUS';
export const MAIN_VISIT = 'MAIN_VISIT';
export const MAIN_TEA_DESCRIPTION = 'MAIN_TEA_DESCRIPTION';
